version: "3.9"

networks:
  gomart-net:
    driver: bridge

services:
 
  ###################################
  # stripe_wrapper: Microservice for communication to stripe
  ###################################
  stripe_wrapper:
    hostname: stripe_wrapper
    build:
      context: app
      dockerfile: stripe_wrapper.Dockerfile
    image: thejustinnl/stripe_wrapper:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

    networks:
      - gomart-net

  #######################################################
  # make_payment: make_payment microservice
  #######################################################
  make_payment:
    hostname: make_payment
    build:
      context: app
      dockerfile: make_payment.Dockerfile
    image: thejustinnl/make_payment:1.0
    ports:
      - "8000:8000"
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      payment_URL: http://stripe_wrapper:5005/pay


    networks:
      - gomart-net
    
 
