version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

    commands:
      - cd $CODEBUILD_SRC_DIR
      - cd UI
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync ./dist s3://gomartttt.store --delete
